export const PLAYLIST_DATA = [
  {
    id: 1,
    title: "Track 1",
    artist: "Unknown Artist",
    duration: "4:30",
    active: true,
    file: "/assets/music/duvet_80s.mp3",
  },
  {
    id: 2,
    title: "Track 2",
    artist: "Unknown Artist",
    duration: "3:24",
    active: false,
    file: "/assets/music/sertab_erener_oyun_bitti.mp3",
  },
  {
    id: 3,
    title: "Track 3",
    artist: "Unknown Artist",
    duration: "4:00",
    active: false,
    file: "/assets/music/demet_akalin_intikam.mp3",
  },
  {
    id: 4,
    title: "Track 4",
    artist: "Unknown Artist",
    duration: "4:18",
    active: false,
    file: "/assets/music/qaraqan_hardadir.mp3",
  },
  {
    id: 5,
    title: "Track 5",
    artist: "Unknown Artist",
    duration: "3:51",
    active: false,
    file: "/assets/music/talking_in_your_sleep_the_romantics.mp3",
  },
  {
    id: 6,
    title: "Track 6",
    artist: "Unknown Artist",
    duration: "4:05",
    active: false,
    file: "/assets/music/virtual_world_fibre.mp3",
  },
];
