export const PLAYLIST_DATA = [
  {
    id: 1,
    title: "Track 1",
    artist: "Unknown Artist",
    duration: "4:05",
    active: true,
    file: "/assets/music/virtual_world_fibre.mp3",
  },
  {
    id: 2,
    title: "Track 2",
    artist: "Unknown Artist",
    duration: "3:51",
    active: false,
    file: "/assets/music/talking_in_your_sleep_the_romantics.mp3",
  },
  {
    id: 3,
    title: "Track 3",
    artist: "Unknown Artist",
    duration: "3:34",
    active: false,
    file: "/assets/music/rich_bitch.mp3",
  },
  {
    id: 4,
    title: "Track 4",
    artist: "Unknown Artist",
    duration: "3:59",
    active: false,
    file: "/assets/music/robert_miles_one_n_one.mp3",
  },
  {
    id: 5,
    title: "Track 5",
    artist: "Unknown Artist",
    duration: "4:04",
    active: false,
    file: "/assets/music/murat_akay_ise_al_beni.mp3",
  },
  {
    id: 6,
    title: "Track 6",
    artist: "Unknown Artist",
    duration: "3:43",
    active: false,
    file: "/assets/music/shahzoda_afghana.mp3",
  },
  {
    id: 7,
    title: "Track 7",
    artist: "Unknown Artist",
    duration: "5:04",
    active: false,
    file: "/assets/music/ella.mp3",
  },
  {
    id: 8,
    title: "Track 8",
    artist: "Unknown Artist",
    duration: "3:50",
    active: false,
    file: "/assets/music/fantasy_jessie_frye.mp3",
  },
  {
    id: 9,
    title: "Track 9",
    artist: "Unknown Artist",
    duration: "4:28",
    active: false,
    file: "/assets/music/plastic_love.mp3",
  },
  {
    id: 10,
    title: "Track 10",
    artist: "Unknown Artist",
    duration: "3:22",
    active: false,
    file: "/assets/music/grimes_genesis.mp3",
  },
];
