export const resumeData = {
  personalInfo: {
    name: "Javad Javadli",
    title: "Frontend Developer",
    email: "ccavad2015@gmail.com",
    // phone: "",
    location: "Azerbaijan, Baku",
    // website: "",
  },
  experience: [
    {
      id: 1,
      role: "Frontend Developer",
      company: "Nanolink MMC",
      period: "May 2025 - Current",
      // description: "",
      highlights: [
        "Developed and maintained a React application integrated with Sigma.js for graph visualization",
      ],
    },
    {
      id: 2,
      role: "Frontend Developer",
      company: "Agile Solutions Azerbaijan",
      period: "August 2023 - February 2025",
      // description: "",
      highlights: [
        "Developed and maintained call center and dialer applications using React",
        "Developed a props-based styling system with responsive design support in React",
        "Mentored programming students",
      ],
    },
    {
      id: 3,
      role: "Intern Frontend Developer",
      company: "Proton.az MMC",
      period: "September 2022 - November 2022",
      // description: "",
      highlights: [
        "Developed landing page websites using vanilla JavaScript and JQuery",
      ],
    },
  ],
  education: [
    {
      id: 1,
      degree: "Mining Engineering",
      institution: "Azerbaijan State Oil and Industry University",
      period: "2014 - 2015",
      // description: "",
    },
  ],
  skills: [
    "React",
    "JavaScript",
    "TypeScript",
    "Next.js",
    "React Native",
    "Node.js",
    "Express js",
    "MongoDB",
    "PostgreSQL",
    "Tanstack Query",
    "Zustand",
    "Redux",
    "Git/GitHub",
    "Chakra UI",
    "Responsive Design",
    "HTML/CSS",
    "Tailwind CSS",
    "Sigma.js",
  ],
};
